### ISSUE TITLE
YUV420 to RGB conversion

### ISSUE THREAD

**Issue by inesachour** [thuanpham98/processing_camera_image#3]
Hello,

Your project is really great. Thank you!

But I have a question regarding the YUV420 to RGB conversion, specifically in this part:

```
rt = round(yp + vp * 1436 / 1024 - 179);
gt = round(yp - up * 46549 / 131072 + 44 - vp * 93604 / 131072 + 91);
bt = round(yp + up * 1814 / 1024 - 227);
```

Could you please provide me with the source of these formulas? I couldn't find them anywhere. All the available resources use different values.

**Comment by thuanpham98** [comment]
Thank you for your reply, this is link:

https://stackoverflow.com/questions/36212904/yuv-420-888-interpretation-on-samsung-galaxy-s7-camera2
.

if you can test this library on IOS, help me and create pull request,
please. Thanks you, from Viet Nam developer.

**Comment by inesachour** [comment]
Thank you for your prompt response. 

Unfortunately, I don't have access to iOS devices at the moment. I will test it as soon as I can.
